version: "3"
services:
  #PHP Service
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_new
    restart: always
    tty: true
    ports:
      - "4400:80"
      - "4433:443"
    networks:
      app-network:
        ipv4_address: 192.168.0.5
    volumes: 
      - .:/app
      - /app/vender

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: web_db_new
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 6000:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cart
      MYSQL_USER: admin
      MYSQL_PASSWORD: Egypt
    networks:
      app-network:
        ipv4_address: 192.168.0.3
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: web_pma_new
    restart: always
    ports:
      - "9000:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      app-network:
        ipv4_address: 192.168.0.4

#Docker Networks
networks:
  app-network:
    external: true
#Volumes
volumes:
  db_data:
    driver: local


